/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

#include <stdint.h>

unsigned short estudiantes = 0;
unsigned char counter_i = 0;

int main(void)
{
	/*Loop forever*/
	while(1){
		estudiantes++;
		counter_i = ~counter_i;
	}
}
